<a href="https://colab.research.google.com/github/AlexisG81/etl-data-pipeline/blob/main/Notebooks/Corredores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd

In [9]:
url = "https://raw.githubusercontent.com/AlexisG81/etl-data-pipeline/refs/heads/main/data/raw/corredores.csv"

In [11]:
df = pd.read_csv(url)

In [12]:
df.head()

   id_corredor               nombre         zona    nivel  anios_experiencia
0            1    José López Flores  Paracentral      Mid                4.0
1            2    José Ortiz García     Centro     Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                 6.0
3            4  Fernanda Rojas Cruz          NaN  SENIOR                 8.0
4            5      Ana Gómez Rojas          NaN   Senior                4.0

In [13]:
df.shape

df.columns

df.info()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_corredor        80 non-null     int64
 1   nombre             80 non-null     object
 2   zona               63 non-null     object
 3   nivel              68 non-null     object
 4   anios_experiencia  76 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 3.3+ KB

id_corredor           0
nombre                0
zona                 17
nivel                12
anios_experiencia     4
dtype: int64

In [14]:
df.columns = df.columns.str.strip().str.lower()

for col in df.select_dtypes(include='object'):
    df[col] = df[col].str.strip()

In [15]:
df['zona'] = df['zona'].fillna('No especificado')

In [16]:
df['nivel'] = df['nivel'].fillna('Desconocido')

In [17]:
df['anios_experiencia'] = df['anios_experiencia'].fillna(df['anios_experiencia'].mean())

In [18]:
df['anios_experiencia'] = df['anios_experiencia'].astype(int)

In [20]:
df = df.drop_duplicates()

In [21]:
df.isnull().sum()

id_corredor          0
nombre               0
zona                 0
nivel                0
anios_experiencia    0
dtype: int64

In [22]:
df.head()

,id_corredor,nombre,zona,nivel,anios_experiencia
0,1,José López Flores,Paracentral,Mid,4
1,2,José Ortiz García,Centro,Junior,0
2,3,María Ramírez Cruz,Centro,SENIOR,6
3,4,Fernanda Rojas Cruz,No especificado,SENIOR,8
4,5,Ana Gómez Rojas,No especificado,Senior,4