Importar Librerias

In [1]:
import pandas as pd
import numpy as np

Conexion a PostgreSQL

In [2]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 41.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [3]:
from sqlalchemy import create_engine
database_url = "postgresql://etl_user:tHTK9P4jdQKFnizhnafqha180KVOLlCf@dpg-d6qu5n6uk2gs73fspecg-a.oregon-postgres.render.com/etl_seguros_uami"
engine = create_engine(database_url)

Cargar Dataset

In [5]:
#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/AlexisG81/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv"

polizas = pd.read_csv(url)

Exploración de datos

In [6]:
polizas.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaN,184,42,15,2,"829,53",NaN,139253.11
1,2,2026/02/16,2408,35,11,12,NaN,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75

In [7]:
polizas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    22739 non-null  object
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            21840 non-null  object
 7   comision         21715 non-null  object
 8   monto_asegurado  21787 non-null  object
dtypes: int64(5), object(4)
memory usage: 1.7+ MB

In [8]:
polizas.isnull().sum()

id_poliza             0
fecha_emision      2411
id_cliente            0
id_corredor           0
id_aseguradora        0
id_tipo_seguro        0
prima              3310
comision           3435
monto_asegurado    3363
dtype: int64

In [9]:
polizas.duplicated().sum()

np.int64(0)

Funciones reutilizables

In [10]:
#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

In [11]:
#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

Aplicar Limpieza

In [12]:
polizas = normalizar_columnas(polizas)
polizas = limpiar_texto(polizas)
polizas = polizas.drop_duplicates()

Funciones especificas

In [25]:
#Convertir fecha a dateTime
polizas["fecha_emision"] = pd.to_datetime(
    polizas["fecha_emision"].astype(str).str.strip(),
    errors="coerce"
)

#limpiar datos monetarios
polizas["prima"] = (
    polizas["prima"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

polizas["prima"] = pd.to_numeric(polizas["prima"], errors="coerce")

In [23]:
polizas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    22739 non-null  datetime64[ns]
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            20150 non-null  float64
 7   comision         14926 non-null  float64
 8   monto_asegurado  10185 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(5)
memory usage: 1.7 MB

In [24]:
polizas.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaT,184,42,15,2,82953.00,NaN,139253.11
1,2,2026-02-16,2408,35,11,12,NaN,NaN,NaN
2,3,2025-02-14,540,42,4,9,1611.53,NaN,NaN
3,4,2026-09-01,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,NaN,NaN,123407.75

Separar validos y rechazados

In [27]:
#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. El id debe ser not null
#2 fechas deben tener un formato valido
#3 los campos monetarios no pueden quedar como null

columnas_obligatorias = [
    "id_poliza",
    "fecha_emision",
    "id_cliente",
    "id_corredor",
    "id_aseguradora",
    "id_tipo_seguro",
    "prima",
    "comision",
    "monto_asegurado"
]

validos = polizas [
 polizas[columnas_obligatorias].notna().all(axis=1)
].copy()

rechazados = polizas [
 polizas[columnas_obligatorias].notna().all(axis=1)
].copy()

rechazados_negativos= polizas[
    (polizas["prima"] < 0) |
    (polizas["comision"] < 0) |
    (polizas["monto_asegurado"] < 0)
].copy()

Motivo del rechazo

In [29]:
def motivo(row):
    motivos = []

    if pd.isna(row["id_poliza"]):
        motivos.append("id_poliza_nulo")

    if pd.isna(row["fecha_emision"]):
        motivos.append("fecha_emision_nulo")

    if pd.isna(row["id_cliente"]):
        motivos.append("id_cliente_nulo")

    if pd.isna(row["id_corredor"]):
        motivos.append("id_corredor_nulo")

    if pd.isna(row["id_aseguradora"]):
        motivos.append("id_aseguradora_nulo")

    if pd.isna(row["id_tipo_seguro"]):
        motivos.append("id_tipo_seguro_nulo")

    if pd.isna(row["prima"]) or row["prima"] < 0:
        motivos.append("prima_invalida")

    if pd.isna(row["comision"]) or row["comision"] < 0:
        motivos.append("comision_invalida")

    if pd.isna(row["monto_asegurado"]) or row["monto_asegurado"] < 0:
        motivos.append("monto_asegurado_invalido")

    return ", ".join(motivos)

Agregar motivo de rechazo

Exportar Archivos

In [30]:
validos.to_csv("polizas_curated.csv", index=False)
rechazados.to_csv("polizas_rejects.csv", index=False)

Cargar datos en PostgreSQL

Para evitar errores de carga y mostrar los detalles

In [31]:
validos.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
3,4,2026-09-01,2821,40,10,5,1866.62,456.99,244461.27
6,7,2025-02-09,1254,25,11,4,1400.82,188.40,258202.93
13,14,2026-01-20,367,65,1,11,0.00,122.12,249504.31
18,19,2025-05-19,1693,50,3,9,1257.43,237.20,106454.95
26,27,2025-06-25,352,30,3,6,-1290.55,179.37,162227.75

In [32]:
validos.dtypes

id_poliza                   int64
fecha_emision      datetime64[ns]
id_cliente                  int64
id_corredor                 int64
id_aseguradora              int64
id_tipo_seguro              int64
prima                     float64
comision                  float64
monto_asegurado           float64
dtype: object

In [33]:
validos.isnull().sum()

id_poliza          0
fecha_emision      0
id_cliente         0
id_corredor        0
id_aseguradora     0
id_tipo_seguro     0
prima              0
comision           0
monto_asegurado    0
dtype: int64

In [34]:
validos.value_counts()

id_poliza  fecha_emision  id_cliente  id_corredor  id_aseguradora  id_tipo_seguro  prima        comision  monto_asegurado
25074      2025-10-05     3748        28           3               7                747.24000   135.51    130681.31          1
25059      2026-02-09     944         39           11              9                352.62000   44.46     67142.37           1
25057      2025-05-29     77          14           12              7                1.29283     184.60    119370.40          1
25052      2025-05-21     581         17           4               5                1.82172     138.86    173431.27          1
25042      2025-09-13     1685        65           8               1                0.00000     132.50    112445.07          1
                                                                                                                            ..
27         2025-06-25     352         30           3               6               -1290.55000  179.37    162227.75          1
19         2025-05-19     1693        50           3               9                1257.43000  237.20    106454.95          1
14         2026-01-20     367         65           1               11               0.00000     122.12    249504.31          1
7          2025-02-09     1254        25           11              4                1400.82000  188.40    258202.93          1
4          2026-09-01     2821        40           10              5                1866.62000  456.99    244461.27          1
Name: count, Length: 4352, dtype: int64

In [35]:
validos.to_sql(
    "polizas",
    engine,
    if_exists="append",
    index=False
  )

352

Validar Carga

In [36]:
pd.read_sql(
    "Select * From polizas Limit 100",
    engine
)

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,4,2026-09-01,2821,40,10,5,1866.62000,456.99,244461.27
1,7,2025-02-09,1254,25,11,4,1400.82000,188.40,258202.93
2,14,2026-01-20,367,65,1,11,0.00000,122.12,249504.31
3,19,2025-05-19,1693,50,3,9,1257.43000,237.20,106454.95
4,27,2025-06-25,352,30,3,6,-1290.55000,179.37,162227.75
...,...,...,...,...,...,...,...,...,...
95,542,2025-12-08,2720,77,5,1,1.67358,247.88,99356.05
96,550,2025-01-01,2740,18,1,4,1856.51000,357.18,221118.70
97,561,2025-09-12,2867,25,1,9,244.84000,21.87,15421.81
98,563,2025-01-29,1398,57,14,8,841.68000,118.23,27662.38
99,576,2025-04-26,3728,26,15,3,1.03492,140.98,56238.72