<a href="https://colab.research.google.com/github/AlexisG81/etl-data-pipeline/blob/main/Notebooks/Poliza.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [4]:
url="https://raw.githubusercontent.com/AlexisG81/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv"

In [5]:
df = pd.read_csv(url)

In [6]:
df.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaN,184,42,15,2,"829,53",NaN,139253.11
1,2,2026/02/16,2408,35,11,12,NaN,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75

In [7]:
df.shape

df.columns

df.info()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    22739 non-null  object
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            21840 non-null  object
 7   comision         21715 non-null  object
 8   monto_asegurado  21787 non-null  object
dtypes: int64(5), object(4)
memory usage: 1.7+ MB

id_poliza             0
fecha_emision      2411
id_cliente            0
id_corredor           0
id_aseguradora        0
id_tipo_seguro        0
prima              3310
comision           3435
monto_asegurado    3363
dtype: int64

In [8]:
df['fecha_emision'] = pd.to_datetime(df['fecha_emision'], errors='coerce')

In [9]:
df['prima'] = df['prima'].astype(str).str.replace(",", ".")
df['comision'] = df['comision'].astype(str).str.replace(",", ".")
df['monto_asegurado'] = df['monto_asegurado'].astype(str).str.replace(",", ".")

In [10]:
df['prima'] = pd.to_numeric(df['prima'], errors='coerce')
df['comision'] = pd.to_numeric(df['comision'], errors='coerce')
df['monto_asegurado'] = pd.to_numeric(df['monto_asegurado'], errors='coerce')

In [11]:
df['prima'] = df['prima'].fillna(df['prima'].mean())
df['comision'] = df['comision'].fillna(df['comision'].mean())
df['monto_asegurado'] = df['monto_asegurado'].fillna(df['monto_asegurado'].mean())

In [12]:
df['prima'] = df['prima'].fillna(df['prima'].mean())
df['comision'] = df['comision'].fillna(df['comision'].mean())
df['monto_asegurado'] = df['monto_asegurado'].fillna(df['monto_asegurado'].mean())

In [13]:
df = df.drop_duplicates()

In [14]:
df.info()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    4522 non-null   datetime64[ns]
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            25150 non-null  float64
 7   comision         25150 non-null  float64
 8   monto_asegurado  25150 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(5)
memory usage: 1.7 MB

id_poliza              0
fecha_emision      20628
id_cliente             0
id_corredor            0
id_aseguradora         0
id_tipo_seguro         0
prima                  0
comision               0
monto_asegurado        0
dtype: int64

In [15]:
df['fecha_emision'] = df['fecha_emision'].fillna(pd.Timestamp('1900-01-01'))

In [16]:
df.isnull().sum()

id_poliza          0
fecha_emision      0
id_cliente         0
id_corredor        0
id_aseguradora     0
id_tipo_seguro     0
prima              0
comision           0
monto_asegurado    0
dtype: int64

In [17]:
df.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,1900-01-01,184,42,15,2,829.53000,166.664819,139253.110000
1,2,2026-02-16,2408,35,11,12,832.04415,12.220000,112667.361393
2,3,1900-01-01,540,42,4,9,1611.53000,92.050000,112667.361393
3,4,1900-01-01,2821,40,10,5,1866.62000,456.990000,244461.270000
4,5,1900-01-01,945,23,9,11,832.04415,324.080000,123407.750000